apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - port: 6379
      name: redis
  selector: 
    app: redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis  
  serviceName: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis 
    spec:
      containers:
        - name: redis
          image: redis
          args: ["--appendonly", "yes", "--save", "900", "1", "--save", "30", "2"]
          ports:
            - containerPort: 6379
              name: redis
          # resources:
          #   limits:
          #     cpu: .50
          #     memory: 1500Mi
          #   requests:
          #     cpu: .25
          #     memory: 1024Mi
          volumeMounts:
            - name: redis-volume
              mountPath: /data/redis
      volumes:
      - name: redis-volume
        emptyDir: {}
