apiVersion: v1
kind: Service
metadata:
  name: squid-redis
spec:
  ports:
    - port: 6379
      name: squid-redis
  selector: 
    app: squid-redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: squid-redis
  labels:
    app: squid-redis
    type: redis
spec:
  selector:
    matchLabels:
      app: squid-redis  
  serviceName: squid-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: squid-redis 
    spec:
      containers:
        - name: squid-redis
          image: redis
          args: ["--appendonly", "yes", "--save", "900", "1", "--save", "30", "2"]
          ports:
            - containerPort: 6379
              name: squid-redis
          # resources:
          #   limits:
          #     cpu: .50
          #     memory: 1500Mi
          #   requests:
          #     cpu: .25
          #     memory: 1024Mi
          volumeMounts:
            - name: squid-redis-volume
              mountPath: /data/redis
      volumes:
      - name: squid-redis-volume
        emptyDir: {}
