apiVersion: apps/v1
kind: Deployment
metadata:
 name: squid-bot
 labels:
  app: squid-bot
  type: discord-bot

spec:
 replicas: 1
 selector:
  matchLabels:
   app: squid-bot
 template:
  metadata:
   labels:
    app: squid-bot
  spec:
    containers:
      - name: squid-bot
        image: squidtoon99/squid:squidbot.k8s.v4.4
        ports:
        - containerPort: 80 
        env:
          - name: redishost
            value: redis://squid-redis.default.svc.cluster.local
    imagePullSecrets:
      - name: regcred